name: Update Stock Data

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 08:00 UTC (adjust as needed)
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests

      - name: Run update_stock_data script
        run: python update_stock_data.py

      - name: Commit changes if stocks.json updated
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update stocks.json [skip ci]"
          add: "stocks.json"